baseurl = "/"
languageCode = "en-us"
title = "vatlab"
publishDir = 'docs'

canonifyurls = true
metaDataFormat = "toml"
theme = "kiss"

copyright = "&copy; <a href=\"https://github.com/vatlab\">Bo Peng</a> 2017"

[params.info]
enableSocial = true

homeTitle = "vatlab"

[params.opengraph.twitter]
page = "ScriptOfScripts" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "ScriptOfScripts"
github = "vatlab"
email = "bpeng@mdanderson.org"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

