baseurl = "http://vatlab.github.io/blog/"
languageCode = "en-us"
title = "vatlab"
publishDir = 'docs'

canonifyurls = true
metaDataFormat = "toml"
theme = "hugo-theme-blueberry-detox"


[taxonomies]
tag = "tags"

[params]
 author = "Bo Peng"
 description = "Bo Peng, MD Anderson Cancer Center/Assistant Professor"
 twitter = "ScriptOfScripts"
 github = "BoPeng"
