baseurl = "https://vatlab.github.io/blog/"
languageCode = "en-us"
title = "vatlab"
publishDir = 'docs'

canonifyurls = true
metaDataFormat = "toml"
theme = "kiss"

copyright = "&copy; <a href=\"https://github.com/vatlab\">Bo Peng</a> 2017"
googleAnalytics = "UA-107286198-1"

[params]
comments = "http://https://github.com/vatlab/blog/issues"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
enableSocial = true

homeTitle = "vatlab"

[params.opengraph.twitter]
page = "ScriptOfScripts" 

[params.social]

twitter = "ScriptOfScripts"
github = "vatlab"
email = "bpeng@mdanderson.org"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

